$objects.Add(@{id=21;name="Anabil Bus";name_bn="আনাবিল বাস";type="Unknown";check_system=$false;time=$null;stops=@("Motijheel","Dainik Bangla Moor","Paltan","Press Club","High Court","Matsya Bhaban","Shahbag","Bangla Motor","Kawran Bazar","Farmgate","Khamar Bari","Agargaon","Taltola","Shewrapara","Kazipara","Mirpur 10","Mirpur 11","Purobi","Pallabi","Mirpur 12")}) | Out-Null
$objects.Add(@{id=22;name="Anabil Suveccha";name_bn="আনাবিল শুভেচ্ছা বাস";type="Unknown";check_system=$false;time=$null;stops=@("Chittagong Road","Sign Board","Matuail","Rayerbag","Shonir Akhra","Jatrabari","Sayedabad","Gulistan","Chankhar Pul","Bakshi Bazar","Azimpur","Nilkhet","New Market","City College","Kalabagan","Dhanmondi 32","Dhanmondi 27","Asad Gate","College Gate","Shishu Mela","Shyamoli","Kallyanpur","Darussalam","Technical","Gabtoli","Amin Bazar","Hemayetpur","Savar","Nobinagar","Baipayl","Zirani Bazar","Nandan Park","Chandra")}) | Out-Null
$objects.Add(@{id=23;name="Anandamoyi Bus";name_bn="আনন্দময়ী বাস";type="Unknown";check_system=$false;time=$null;stops=@("Motijheel","Gulistan","GPO","Paltan","Press Club","High Court","Shahbag","Bata Signal","Science Lab","City College","Jigatola","Dhanmondi 15","Star Kabab","Shankar","Mohammadpur","Bosila","Ghatar Char")}) | Out-Null
$objects.Add(@{id=24;name="Ananda Bus";name_bn="আনন্দ বাস";type="Unknown";check_system=$false;time=$null;stops=@("Sadarghat","Ray Saheb Bazar","Naya Bazar","Golap Shah Mazar","GPO","Paltan","Press Club","High Court","Matsya Bhaban","Shahbag","Bangla Motor","Kawran Bazar","Farmgate","Khamar Bari","Agargaon","Taltola","Shewrapara","Kazipara","Mirpur 10","Mirpur 11","Purobi","Pallabi","Mirpur 12")}) | Out-Null
$objects.Add(@{id=25;name="Anandas Bus";name_bn="আনন্দস বাস";type="Unknown";check_system=$false;time=$null;stops=@("Gabtoli","Beribadh Tin Rastar Moor","Rayer Bazar","Sikder Medical College","Hazaribag","Nawabganj","Kamrangirchar","Showari Ghat","Mitford Ghat","Babubazar")}) | Out-Null
$objects.Add(@{id=26;name="Ananna Bus";name_bn="অনন্যা বাস";type="Unknown";check_system=$false;time=$null;stops=@("Fulbaria","Chankhar Pul","Bakshi Bazar","Azimpur","Nilkhet","New Market","City College","Kalabagan","Dhanmondi 32","Dhanmondi 27","Asad Gate","College Gate","Shishu Mela","Shyamoli","Kallyanpur","Darussalam","Technical","Gabtoli","Amin Bazar","Hemayetpur","Savar","Nobinagar","Baipayl","Zirani Bazar","Nandan Park","Chandra")}) | Out-Null
$objects.Add(@{id=27;name="Ankoor Bus";name_bn="অংকুর বাস";type="Sitting";check_system=$true;time=$null;stops=@("Motijheel","Gulistan","GPO","Paltan","Kakrail","Shantinagar","Malibagh Moor","Mouchak","Mogbazar","Satrasta","Nabisco","Mohakhali","Chairman Bari","Banani","Kakali","Staff Road","MES","Shewra","Kuril Bishwa Road","Khilkhet","Airport","Jashimuddin (Uttara)","Rajlakshmi","Azampur","House Building","Abdullahpur","Kamarpara")}) | Out-Null
$objects.Add(@{id=28;name="Apel Bus";name_bn="এপেল বাস";type="Unknown";check_system=$false;time=$null;stops=@("Chiriyakhana","Mirpur 1","Ansar Camp","Technical","Kallyanpur","Shyamoli","Shishu Mela","College Gate","Asad Gate","Dhanmondi 27","Shukrabad","Dhanmondi 32","Kalabagan","City College","Science Lab","Bata Signal","Shahbag","Matsya Bhaban","High Court","Press Club","Paltan","GPO","Gulistan","Motijheel","Arambagh")}) | Out-Null
$objects.Add(@{id=29;name="Arab Paribahan";name_bn="আরব পরিবহন বাস";type="Unknown";check_system=$false;time=$null;stops=@("Chiriyakhana","Mirpur 1","Ansar Camp","Technical","Kallyanpur","Shyamoli","Shishu Mela","College Gate","Asad Gate","Shankar","Jigatola","City College","Science Lab","Katabon","Shahbag","Matsya Bhaban","High Court","Press Club","Paltan","GPO","Gulistan","Motijheel")}) | Out-Null
$objects.Add(@{id=30;name="Asad Transport";name_bn="আসাদ ট্রান্সপোর্ট বাস";type="Unknown";check_system=$false;time=$null;stops=@("Chittagong Road","Sign Board","Matuail","Rayerbag","Shonir Akhra","Jatrabari","Sayedabad","Gulistan","GPO","Paltan","Press Club","High Court","Matsya Bhaban","Shahbag","Bangla Motor","Kawran Bazar","Farmgate","Khamar Bari","Agargaon","Taltola","Shewrapara","Kazipara","Mirpur 10")}) | Out-Null
$objects.Add(@{id=31;name="Ashari Bus";name_bn="আশারি বাস";type="Unknown";check_system=$false;time=$null;stops=@("Motijheel","Gulistan","GPO","Paltan","Press Club","High Court","Matsya Bhaban","Shahbag","Bata Signal","Science Lab","City College","Jigatola","Dhanmondi 15","Star Kabab","Shankar","Mohammadpur")}) | Out-Null
$objects.Add(@{id=32;name="Asian Sea";name_bn="এশিয়ান সী বাস";type="Sitting";check_system=$true;time=null;stops=@("Jatrabari","Sayedabad","Gulistan","GPO","Paltan","Kakrail","Shantinagar","Malibagh Moor","Mouchak","Mogbazar","Satrasta","Nabisco","Mohakhali","Chairman Bari","Banani","Kakali","Staff Road","MES","Shewra","Kuril Bishwa Road","Khilkhet","Airport","Jashimuddin (Uttara)","Rajlakshmi","Azampur","House Building","Abdullahpur","Kamarpara")}) | Out-Null
$objects.Add(@{id=33;name="Atish Dipankar";name_bn="অতীশ দীপঙ্কর বাস";type="Unknown";check_system=$false;time=$null;stops=@("Motijheel","Gulistan","GPO","Paltan","Press Club","High Court","Matsya Bhaban","Shahbag","Bangla Motor","Kawran Bazar","Farmgate","Khamar Bari","Agargaon","Taltola","Shewrapara","Kazipara","Mirpur 10","Mirpur 11","Purobi","Pallabi","Mirpur 12")}) | Out-Null
$objects.Add(@{id=34;name="Atomia Bus";name_bn="এটমিয়া বাস";type="Unknown";check_system=$false;time=$null;stops=@("Bosila","Mohammadpur","Asad Gate","College Gate","Shishu Mela","Shyamoli","Kallyanpur","Darussalam","Technical","Gabtoli","Amin Bazar","Hemayetpur","Savar","Nobinagar","Baipayl","Zirani Bazar","Nandan Park","Chandra")}) | Out-Null
$objects.Add(@{id=35;name="Atomia Bus (2)";name_bn="এটমিয়া বাস ২";type="Unknown";check_system=$false;time=$null;stops=@("Chittagong Road","Sign Board","Matuail","Rayerbag","Shonir Akhra","Jatrabari","Sayedabad","Gulistan","Chankhar Pul","Bakshi Bazar","Azimpur","Nilkhet","New Market","City College","Kalabagan","Dhanmondi 32","Dhanmondi 27","Asad Gate","Shyamoli","Kallyanpur","Technical","Gabtoli")}) | Out-Null
$objects.Add(@{id=36;name="Azmeri Bus";name_bn="আজমেরী বাস";type="Unknown";check_system=$false;time=$null;stops=@("Gulistan","GPO","Paltan","Press Club","High Court","Matsya Bhaban","Shahbag","Bangla Motor","Kawran Bazar","Farmgate","Khamar Bari","Agargaon","Taltola","Shewrapara","Kazipara","Mirpur 10","Mirpur 11","Purobi","Pallabi","Mirpur 12")}) | Out-Null
$objects.Add(@{id=37;name="Badda Paribahan";name_bn="বাড্ডা পরিবহন বাস";type="Sitting";check_system=$true;time=null;stops=@("Motijheel","Gulistan","GPO","Paltan","Kakrail","Shantinagar","Malibagh Moor","Mouchak","Mogbazar","Satrasta","Nabisco","Mohakhali","Chairman Bari","Banani","Kakali","Staff Road","MES","Shewra","Kuril Bishwa Road","Khilkhet","Airport","Jashimuddin (Uttara)","Rajlakshmi","Azampur","House Building","Abdullahpur","Kamarpara")}) | Out-Null
$objects.Add(@{id=38;name="Badsha Mia";name_bn="বাদশা মিয়া বাস";type="Unknown";check_system=$false;time=$null;stops=@("Motijheel","Gulistan","GPO","Paltan","Press Club","High Court","Matsya Bhaban","Shahbag","Bata Signal","Science Lab","City College","Jigatola","Dhanmondi 15","Star Kabab","Shankar","Mohammadpur","Ghatar Char","Bosila")}) | Out-Null
$objects.Add(@{id=39;name="Balaka Bus";name_bn="বলাকা বাস";type="Unknown";check_system=$false;time=$null;stops=@("Motijheel","Gulistan","GPO","Paltan","Kakrail","Shantinagar","Malibagh Moor","Mouchak","Mogbazar","Nabisco","Mohakhali","Chairman Bari","Banani","Kakali","Staff Road","MES","Shewra","Kuril Bishwa Road","Khilkhet","Airport","Jashimuddin (Uttara)","Rajlakshmi","Azampur","House Building","Abdullahpur")}) | Out-Null
$objects.Add(@{id=40;name="Balaka Bihanga";name_bn="বলাকা বিহঙ্গ বাস";type="Unknown";check_system=$false;time=$null;stops=@("Gabtoli","Beribadh Tin Rastar Moor","Rayer Bazar","Sikder Medical College","Hazaribag","Nawabganj","Kamrangirchar","Showari Ghat","Mitford Ghat","Babubazar")}) | Out-Null
