// File generated by FlutterFire CLI.
// Run `flutterfire configure --project=faretrackbd` to regenerate.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVT0oorPNyXppM7YcmPtT9sdo1nVAwxek',
    appId: '1:680894620786:web:8293a9b556a7231d254eeb',
    messagingSenderId: '680894620786',
    projectId: 'faretrackbd',
    authDomain: 'faretrackbd.firebaseapp.com',
    databaseURL: 'https://faretrackbd-default-rtdb.firebaseio.com',
    storageBucket: 'faretrackbd.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVT0oorPNyXppM7YcmPtT9sdo1nVAwxek',
    appId: '1:680894620786:android:8293a9b556a7231d254eeb',
    messagingSenderId: '680894620786',
    projectId: 'faretrackbd',
    databaseURL: 'https://faretrackbd-default-rtdb.firebaseio.com',
    storageBucket: 'faretrackbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVT0oorPNyXppM7YcmPtT9sdo1nVAwxek',
    appId: '1:680894620786:ios:8293a9b556a7231d254eeb',
    messagingSenderId: '680894620786',
    projectId: 'faretrackbd',
    databaseURL: 'https://faretrackbd-default-rtdb.firebaseio.com',
    storageBucket: 'faretrackbd.appspot.com',
    iosBundleId: 'com.faretrackbd.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVT0oorPNyXppM7YcmPtT9sdo1nVAwxek',
    appId: '1:680894620786:ios:8293a9b556a7231d254eeb',
    messagingSenderId: '680894620786',
    projectId: 'faretrackbd',
    databaseURL: 'https://faretrackbd-default-rtdb.firebaseio.com',
    storageBucket: 'faretrackbd.appspot.com',
    iosBundleId: 'com.faretrackbd.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVT0oorPNyXppM7YcmPtT9sdo1nVAwxek',
    appId: '1:680894620786:web:8293a9b556a7231d254eeb',
    messagingSenderId: '680894620786',
    projectId: 'faretrackbd',
    authDomain: 'faretrackbd.firebaseapp.com',
    databaseURL: 'https://faretrackbd-default-rtdb.firebaseio.com',
    storageBucket: 'faretrackbd.appspot.com',
  );
}
