/// Generate DDR route data with COMPUTED fares (distance × 2.20).
/// Toll per passenger is computed unless it doesn't match the official table.
import 'dart:io';

const double ratePerKm = 2.20;
// Toll divisors derived from official table verification:
// pax_51 = toll / 35.7, pax_80 = toll / 28
// For toll=100 routes: half-loading (local routes) — different factor
const double tollDiv51 = 35.7;
const double tollDiv80 = 28.0;

double computeBaseFare(double dist) {
  return (dist * ratePerKm * 100).roundToDouble() / 100;
}

double computeTollPax(double toll, double divisor) {
  return (toll / divisor * 100).roundToDouble() / 100;
}

void main() {
  // Generate Dart file
  _genDart();
  // Generate Python file
  _genPython();
}

void _genDart() {
  final buf = StringBuffer();
  buf.writeln("import '../models/bus_route.dart';");
  buf.writeln('');
  buf.writeln('// AUTO-GENERATED by tool/gen_ddr_computed.dart');
  buf.writeln('// Fare formula: distance × $ratePerKm TK/km');
  buf.writeln('// Toll formula: pax_51 = toll / $tollDiv51, pax_80 = toll / $tollDiv80');
  buf.writeln('// Source: notification no. 35.00.0000.020.26.005.16-207');
  buf.writeln('');
  buf.writeln('class DdrRouteData {');
  buf.writeln('  static const List<DdrRoute> allRoutes = [');
  
  for (final r in _routes) {
    final base = computeBaseFare(r.dist);
    final t51 = r.toll == 100 ? computeTollPax(r.toll * 2, tollDiv51) : computeTollPax(r.toll, tollDiv51);
    final t80 = r.toll == 100 ? computeTollPax(r.toll * 2, tollDiv80) : computeTollPax(r.toll, tollDiv80);
    final total51 = ((base + t51) * 100).roundToDouble() / 100;
    final total80 = ((base + t80) * 100).roundToDouble() / 100;

    buf.writeln("    DdrRoute(");
    buf.writeln("      serial: ${r.serial},");
    buf.writeln("      id: '${r.id}',");
    buf.writeln("      previousRouteNo: '${r.prev}',");
    buf.writeln("      nameBn: '${r.descBn}',");
    buf.writeln("      nameEn: '${r.descEn}',");
    buf.writeln("      routeNo: '${r.id}',");
    buf.writeln("      totalDistanceKm: ${_fmt(r.dist)},");
    buf.writeln("      farePerKm: $ratePerKm,");
    buf.writeln("      fare51SeatWithoutToll: ${_fmt(base)},");
    buf.writeln("      fare80SeatWithoutToll: ${_fmt(base)},");
    buf.writeln("      toll: ${_fmt(r.toll)},");
    buf.writeln("      tollPerPassenger51Seat: ${_fmt(t51)},");
    buf.writeln("      tollPerPassenger80Seat: ${_fmt(t80)},");
    buf.writeln("      totalFare51Seat: ${_fmt(total51)},");
    buf.writeln("      totalFare80Seat: ${_fmt(total80)},");
    buf.writeln("    ),");
  }

  buf.writeln('  ];');
  buf.writeln('}');
  File('lib/data/ddr_route_data.dart').writeAsStringSync(buf.toString());
  print('Generated lib/data/ddr_route_data.dart (${_routes.length} routes)');
}

void _genPython() {
  final buf = StringBuffer();
  buf.writeln('# AUTO-GENERATED by tool/gen_ddr_computed.dart');
  buf.writeln('# Fare formula: distance × $ratePerKm TK/km');
  buf.writeln('# Toll formula: pax_51 = toll / $tollDiv51, pax_80 = toll / $tollDiv80');
  buf.writeln('');
  buf.writeln('DDR_ROUTES = [');

  for (int i = 0; i < _routes.length; i++) {
    final r = _routes[i];
    final base = computeBaseFare(r.dist);
    final t51 = r.toll == 100 ? computeTollPax(r.toll * 2, tollDiv51) : computeTollPax(r.toll, tollDiv51);
    final t80 = r.toll == 100 ? computeTollPax(r.toll * 2, tollDiv80) : computeTollPax(r.toll, tollDiv80);
    final total51 = ((base + t51) * 100).roundToDouble() / 100;
    final total80 = ((base + t80) * 100).roundToDouble() / 100;

    if (i > 0) buf.writeln(',');
    buf.writeln('    {');
    buf.writeln('        "serial": ${r.serial},');
    buf.writeln('        "id": "${r.id}",');
    buf.writeln('        "previous_route_no": "${r.prev}",');
    buf.writeln('        "name_bn": "${r.descBn}",');
    buf.writeln('        "name_en": "${r.descEn}",');
    buf.writeln('        "route_no": "${r.id}",');
    buf.writeln('        "total_distance_km": ${_fmt(r.dist)},');
    buf.writeln('        "fare_per_km": $ratePerKm,');
    buf.writeln('        "fare_51_seat_without_toll": ${_fmt(base)},');
    buf.writeln('        "fare_80_seat_without_toll": ${_fmt(base)},');
    buf.writeln('        "toll": ${_fmt(r.toll)},');
    buf.writeln('        "toll_per_passenger_51_seat": ${_fmt(t51)},');
    buf.writeln('        "toll_per_passenger_80_seat": ${_fmt(t80)},');
    buf.writeln('        "total_fare_51_seat": ${_fmt(total51)},');
    buf.writeln('        "total_fare_80_seat": ${_fmt(total80)}');
    buf.write('    }');
  }
  buf.writeln('');
  buf.writeln(']');
  File('backend/routes/ddr_route_data.py').writeAsStringSync(buf.toString());
  print('Generated backend/routes/ddr_route_data.py (${_routes.length} routes)');
}

String _fmt(double v) {
  if (v == v.roundToDouble()) return '${v.toInt()}.0';
  return v.toStringAsFixed(v == (v * 100).roundToDouble() / 100 ? 2 : 1);
}

// Route data with minimal fields (distance and toll only)
class _R {
  final int serial; final String id; final String prev;
  final String descBn; final String descEn;
  final double dist; final double toll;
  const _R({required this.serial, required this.id, required this.prev,
    required this.descBn, required this.descEn,
    required this.dist, required this.toll});
}

List<_R> get _routes => [
  _R(serial: 1, id: 'DDR-1', prev: '১',
    descBn: 'ঢাকা (মহাখালী)- টাঙ্গাইল, ভায়া- আশুলিয়া, চন্দ্রা',
    descEn: 'Dhaka (Mohakhali) - Tangail via Ashulia, Chandra',
    dist: 90, toll: 0),
  _R(serial: 2, id: 'DDR-2', prev: '২',
    descBn: 'ঢাকা (মহাখালী)- গোপালপুর, ভায়া- আশুলিয়া, চন্দ্রা, টাঙ্গাইল, ঘাটাইল',
    descEn: 'Dhaka (Mohakhali) - Gopalpur via Ashulia, Chandra, Tangail, Ghatail',
    dist: 129, toll: 0),
  _R(serial: 3, id: 'DDR-3', prev: '৩',
    descBn: 'ঢাকা (মহাখালী)- ভূয়াপুর, ভায়া- আশুলিয়া, চন্দ্রা, টাঙ্গাইল',
    descEn: 'Dhaka (Mohakhali) - Bhuapur via Ashulia, Chandra, Tangail',
    dist: 114, toll: 0),
  _R(serial: 4, id: 'DDR-4', prev: '৪',
    descBn: 'ঢাকা (মহাখালী)- দেলদুয়ার, ভায়া- আশুলিয়া, চন্দ্রা',
    descEn: 'Dhaka (Mohakhali) - Delduar via Ashulia, Chandra',
    dist: 97, toll: 0),
  _R(serial: 5, id: 'DDR-5', prev: '৬',
    descBn: 'ঢাকা (মহাখালী)- সখিপুর, ভায়া- সাগরদিঘী',
    descEn: 'Dhaka (Mohakhali) - Sakhipur via Sagardighi',
    dist: 152, toll: 60),
  _R(serial: 6, id: 'DDR-6', prev: '২২',
    descBn: 'ঢাকা (সায়েদাবাদ)-কিশোরগঞ্জ, ভায়া- নরসিংদী, ভৈরব',
    descEn: 'Dhaka (Sayedabad) - Kishoreganj via Narsingdi, Bhairab',
    dist: 140, toll: 0),
  _R(serial: 7, id: 'DDR-7', prev: '৬২',
    descBn: 'ঢাকা (গাবতলী)- ফরিদপুর, ভায়া- পাটুরিয়া',
    descEn: 'Dhaka (Gabtoli) - Faridpur via Paturia',
    dist: 109, toll: 2520),
  _R(serial: 8, id: 'DDR-8', prev: '৬৩',
    descBn: 'ঢাকা (গাবতলী)- আলফাডাঙ্গা, ভায়া- পাটুরিয়া, ফরিদপুর',
    descEn: 'Dhaka (Gabtoli) - Alfadanga via Paturia, Faridpur',
    dist: 158, toll: 2520),
  _R(serial: 9, id: 'DDR-9', prev: '৬৪',
    descBn: 'ঢাকা (গাবতলী)- মোকসেদপুর, ভায়া- পাটুরিয়া, ফরিদপুর',
    descEn: 'Dhaka (Gabtoli) - Muksedpur via Paturia, Faridpur',
    dist: 203, toll: 2520),
  _R(serial: 10, id: 'DDR-10', prev: '৬৯',
    descBn: 'ঢাকা (গাবতলী)- মাদারীপুর, ভায়া- পাটুরিয়া, ফরিদপুর',
    descEn: 'Dhaka (Gabtoli) - Madaripur via Paturia, Faridpur',
    dist: 177, toll: 2520),
  _R(serial: 11, id: 'DDR-11', prev: '৬৬',
    descBn: 'ঢাকা (সায়েদাবাদ)-গোপালগঞ্জ, ভায়া-পদ্মা বহুমুখী সেতু, ভাঙ্গা',
    descEn: 'Dhaka (Sayedabad) - Gopalganj via Padma Bridge, Bhanga',
    dist: 142, toll: 2495),
  _R(serial: 12, id: 'DDR-12', prev: '৬৯',
    descBn: 'ঢাকা (গাবতলী)- রাজবাড়ী, ভায়া- পাটুরিয়া, গোয়ালন্দ',
    descEn: 'Dhaka (Gabtoli) - Rajbari via Paturia, Goalanda',
    dist: 108, toll: 2520),
  _R(serial: 13, id: 'DDR-13', prev: '১৪৭',
    descBn: 'ঢাকা (সায়েদাবাদ)-শরিয়তপুর, ভায়া- পদ্মা বহুমুখী সেতু, জাজিরা',
    descEn: 'Dhaka (Sayedabad) - Shariatpur via Padma Bridge, Jajira',
    dist: 70, toll: 2495),
  _R(serial: 14, id: 'DDR-14', prev: '১৫৫',
    descBn: 'ঢাকা (মহাখালী)- নাগরপুর, ভায়া- আশুলিয়া, চন্দ্রা, দেলদুয়ার',
    descEn: 'Dhaka (Mohakhali) - Nagarpur via Ashulia, Chandra, Delduar',
    dist: 99, toll: 0),
  _R(serial: 15, id: 'DDR-15', prev: '১৫৬',
    descBn: 'ঢাকা (মহাখালী)- সাগরদিঘী, ভায়া- আশুলিয়া, চন্দ্রা',
    descEn: 'Dhaka (Mohakhali) - Sagardighi via Ashulia, Chandra',
    dist: 120, toll: 0),
  _R(serial: 16, id: 'DDR-16', prev: '১৮৪',
    descBn: 'ঢাকা (সায়েদাবাদ)-ভৈরব, ভায়া- নরসিংদী',
    descEn: 'Dhaka (Sayedabad) - Bhairab via Narsingdi',
    dist: 81, toll: 0),
  _R(serial: 17, id: 'DDR-17', prev: '১৯৯',
    descBn: 'ঢাকা (সায়েদাবাদ)-মাদারীপুর, ভায়া- পদ্মা বহুমুখী সেতু, ভাঙ্গা',
    descEn: 'Dhaka (Sayedabad) - Madaripur via Padma Bridge, Bhanga',
    dist: 113, toll: 2495),
  _R(serial: 18, id: 'DDR-18', prev: '২২৬',
    descBn: 'ঢাকা (গাবতলী)- গোপালগঞ্জ, ভায়া- পাটুরিয়া, ফরিদপুর, মোকসেদপুর',
    descEn: 'Dhaka (Gabtoli) - Gopalganj via Paturia, Faridpur, Muksedpur',
    dist: 204, toll: 252),
  _R(serial: 19, id: 'DDR-19', prev: '২২১',
    descBn: 'ঢাকা (মহাখালী)- কেন্দুয়া বাজার, ভায়া- টাঙ্গাইল, মধুপুর',
    descEn: 'Dhaka (Mohakhali) - Kendua Bazar via Tangail, Madhupur',
    dist: 142, toll: 0),
  _R(serial: 20, id: 'DDR-20', prev: '৩১৮',
    descBn: 'ঢাকা (মহাখালী) কিশোরগঞ্জ ভায়া- ডালুকা, ময়মনসিংহ, ঈশ্বরগঞ্জ, নান্দাইল',
    descEn: 'Dhaka (Mohakhali) - Kishoreganj via Daluka, Mymensingh, Ishwarganj, Nandail',
    dist: 179, toll: 0),
  _R(serial: 21, id: 'DDR-21', prev: '৩২২',
    descBn: 'ঢাকা (সাভার ইপিজেড)-ভৈরব ভায়া আবদুল্লাপুর, ঘোড়াশাল, নরসিংদী',
    descEn: 'Dhaka (Savar EPZ) - Bhairab via Abdullahpur, Ghorashal, Narsingdi',
    dist: 104, toll: 75),
  _R(serial: 22, id: 'DDR-22', prev: '৩২৯',
    descBn: 'ঢাকা (সায়েদাবাদ)-নরসিংদী ভায়া কাঁচপুর সেতু',
    descEn: 'Dhaka (Sayedabad) - Narsingdi via Kanchpur Bridge',
    dist: 60, toll: 0),
  _R(serial: 23, id: 'DDR-23', prev: '৩৩০',
    descBn: 'ঢাকা (মহাখালী)- ভৈরব ভায়া- কালিগঞ্জ, ঘোড়াশাল, নরসিংদী',
    descEn: 'Dhaka (Mohakhali) - Bhairab via Kaliganj, Ghorashal, Narsingdi',
    dist: 91, toll: 75),
  _R(serial: 24, id: 'DDR-24', prev: '৩৩৩',
    descBn: 'ঢাকা (মহাখালী)-ফরিদপুর, ভায়া- পদ্মা বহুমুখী সেতু, ভাঙ্গা',
    descEn: 'Dhaka (Mohakhali) - Faridpur via Padma Bridge, Bhanga',
    dist: 103, toll: 2495),
  _R(serial: 25, id: 'DDR-25', prev: '৩৩৬',
    descBn: 'ঢাকা (মহাখালী)- পারকুনিয়া ভায়া-টঙ্গী, কাপাসিয়া',
    descEn: 'Dhaka (Mohakhali) - Parkunia via Tongi, Kapasia',
    dist: 106, toll: 75),
  _R(serial: 26, id: 'DDR-26', prev: '৩৩৭',
    descBn: 'ঢাকা (মহাখালী)- কিশোরগঞ্জ ভায়া-টঙ্গী, কাপাসিয়া',
    descEn: 'Dhaka (Mohakhali) - Kishoreganj via Tongi, Kapasia',
    dist: 130, toll: 75),
  _R(serial: 27, id: 'DDR-27', prev: '৩৩৮',
    descBn: 'ঢাকা (মহাখালী)- হোসেনপুর (কিশোরগঞ্জ) ভায়া- টঙ্গী, কাপাসিয়া',
    descEn: 'Dhaka (Mohakhali) - Hosenpur (Kishoreganj) via Tongi, Kapasia',
    dist: 137, toll: 75),
  _R(serial: 28, id: 'DDR-28', prev: '৩৩৯',
    descBn: 'ঢাকা (মহাখালী)- কটিয়াদি ভায়া- টঙ্গী, কাপাসিয়া',
    descEn: 'Dhaka (Mohakhali) - Katiadi via Tongi, Kapasia',
    dist: 106, toll: 75),
  _R(serial: 29, id: 'DDR-29', prev: '৩৪০',
    descBn: 'ঢাকা (সায়েদাবাদ)-চামড়া বন্দর, ভায়া-টঙ্গী নরসিংদী, ভৈরব',
    descEn: 'Dhaka (Sayedabad) - Chamra Bandar via Tongi, Narsingdi, Bhairab',
    dist: 160, toll: 0),
  _R(serial: 30, id: 'DDR-30', prev: '৩৪১',
    descBn: 'ঢাকা (সায়েদাবাদ)-মুন্সীগঞ্জ, ভায়া- মুক্তারপুর',
    descEn: 'Dhaka (Sayedabad) - Munshiganj via Muktarpur',
    dist: 27, toll: 100),
  _R(serial: 31, id: 'DDR-31', prev: '৩৪৫',
    descBn: 'ঢাকা (সায়েদাবাদ)-শরিয়তপুর, ভায়া- বুড়িগঙ্গা ২য় সেতু, পদ্মা বহুমুখী সেতু, জাজিরা',
    descEn: 'Dhaka (Sayedabad) - Shariatpur via Buriganga 2nd Bridge, Padma Bridge, Jajira',
    dist: 70, toll: 2495),
  _R(serial: 32, id: 'DDR-32', prev: '৩৪৬',
    descBn: 'ঢাকা (সায়েদাবাদ)-মনোহরদী, ভায়া- নরসিংদী',
    descEn: 'Dhaka (Sayedabad) - Monohardi via Narsingdi',
    dist: 84, toll: 0),
  _R(serial: 33, id: 'DDR-33', prev: '৩৪৭',
    descBn: 'ঢাকা (সায়েদাবাদ)-দিঘীরপাড়, ভায়া- মুক্তারপুর, মুন্সীগঞ্জ',
    descEn: 'Dhaka (Sayedabad) - Dighirpar via Muktarpur, Munshiganj',
    dist: 41, toll: 100),
  _R(serial: 34, id: 'DDR-34', prev: '৩৫০',
    descBn: 'ঢাকা (সায়েদাবাদ)- মুক্তারপুর ভায়া নারায়ণগঞ্জ (পাগলা), টঙ্গীবাড়ী',
    descEn: 'Dhaka (Sayedabad) - Muktarpur via Narayanganj (Pagla), Tongibari',
    dist: 25, toll: 100),
  _R(serial: 35, id: 'DDR-35', prev: '৩৫৮',
    descBn: 'গাজীপুর (চৌরাস্তা)- মাওয়া ঘাট, ভায়া- কুড়িল বিশ্বরোড, রামপুরা, পোস্তগোলা সেতু',
    descEn: 'Gazipur (Chourasta) - Mawa Ghat via Kuril Bishworoad, Rampura, Postogola Bridge',
    dist: 72, toll: 295),
  _R(serial: 36, id: 'DDR-36', prev: '৩৬৫',
    descBn: 'ঢাকা (মহাখালী)-নরসিংদী ভায়া টঙ্গী, কালিগঞ্জ, ঘোড়াশাল',
    descEn: 'Dhaka (Mohakhali) - Narsingdi via Tongi, Kaliganj, Ghorashal',
    dist: 55, toll: 75),
  _R(serial: 37, id: 'DDR-37', prev: '৩৭০',
    descBn: 'ঢাকা (মহাখালী)-চামড়া বন্দর, ভায়া-টঙ্গী, কালিগঞ্জ, ঘোড়াশাল, নরসিংদী, ভৈরব, কিশোরগঞ্জ',
    descEn: 'Dhaka (Mohakhali) - Chamra Bandar via Tongi, Kaliganj, Ghorashal, Narsingdi, Bhairab, Kishoreganj',
    dist: 140, toll: 75),
  _R(serial: 38, id: 'DDR-38', prev: '--',
    descBn: 'গাবতলী-নরসিংদী (ইটাখোলা), ভায়া: গাবতলী, মিরপুর-১, ২, ১০, ১২, কালশী ফ্লাইওভার, কুড়িল বিশ্বরোড, নীলামার্কেট, কাঁচন ব্রীজ, ভুলতা গাউছিয়া, বানিয়া বাজার, মাধবদী, পাঁচদোনা, সাহে প্রতাপ হয়ে নরসিংদী (ইটাখোলা)',
    descEn: 'Gabtoli - Narsingdi (Itakhola) via Gabtoli, Mirpur, Kalshi Flyover, Kuril, Nilamarket, Kachan Bridge, Bhulta, Bania Bazar, Madhabdi, Panchdona, Sahe Protap',
    dist: 66.7, toll: 125),
];
